import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import InputField from "../components/InputField";
import Blog from "../components/ReduxTest";
export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Add your Bookmark</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <InputField />
        <Blog />
      </main>
    </div>
  );
}
